### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by takasan2024** [takasan2024/furima-40238#20]
＃URL
https://furima-40238.onrender.com

Basic認証のIDとパスワード
ID：takahiro パスワード：0987

出品者用のメールアドレスとパスワード
メールアドレス：hikari@hikari.com  パスワード：HIKARI1

購入者用のメールアドレスとパスワード
メールアドレス：sample@sample.com  パスワード：takun9

**Comment by kubota-tec** [comment]
@takasan2024 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いいたします！

**[修正依頼箇所]**

- [x] **パスワードは、半角英数字混合での入力が必須であること**
現状、数字のみでも登録が可能です。

- [x] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
商品出品時に入力に問題がある状態で「出品する」ボタンが押され出品ページに戻った際にも、販売手数料や販売利益が計算されるようにしましょう。
現在、リダイレクト後に金額入力欄に変化を加えても数料と販売利益が表示されません。
そのため解消をしていただき、再度ご提出をお願いいたします。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いいたします。

**Comment by takasan2024** [comment]
上記内容を修正し、本番環境でも正しく動作することを確認しました。
ご確認のほど、よろしくお願いします。
＃URL
https://furima-40238.onrender.com/

Basic認証のIDとパスワード
ID：takahiro パスワード：0987

出品者用のメールアドレスとパスワード
メールアドレス：[hikari@hikari.com](mailto:hikari@hikari.com) パスワード：HIKARI1

購入者用のメールアドレスとパスワード
メールアドレス：[sample@sample.com](mailto:sample@sample.com) パスワード：takun9

**Comment by mizuki-ueda** [comment]
takasan2024さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
